version: '3'

services:

  nginx:
    image: nginx:1.13
    ports:
      - 80:80
    volumes:
      - ./html:/var/www/html
      - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php_srv_1
      - php_srv_2
      - php_srv_3
      - php_srv_4

  php_srv_1:
    image: phpstorm/php-72-apache-xdebug-27
    ports:
      - 8101:80
    volumes:
      - ./html:/var/www/html
      - ./html/php_srv_1:/var/www/html/env
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal

  php_srv_2:
    image: phpstorm/php-72-apache-xdebug-27
    ports:
      - 8102:80
    volumes:
      - ./html:/var/www/html
      - ./html/php_srv_2:/var/www/html/env
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal

  php_srv_3:
    image: phpstorm/php-72-apache-xdebug-27
    ports:
      - 8103:80
    volumes:
      - ./html:/var/www/html
      - ./html/php_srv_3:/var/www/html/env
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal

  php_srv_4:
    image: phpstorm/php-72-apache-xdebug-27
    ports:
      - 8104:80
    volumes:
      - ./html:/var/www/html
      - ./html/php_srv_4:/var/www/html/env
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal
